name: Pack and release

# Run the workflow when changes are pushed to develop
on:
 push:
  branches: [ develop ]

jobs:

 release:
  # Only release on push to develop
  if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
     node-version: 15.x

  - name: Install
    run: npm ci

  - name: npx version
    run: npx -v

  - name: Release
    run: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     GIT_AUTHOR_NAME: "semantic-release-bot"
     GIT_AUTHOR_EMAIL: "semantic-release-bot"
     # We need someone with admin permissions to commit from CI in possibly protected branches
     GIT_COMMITTER_NAME: "Gonzalo Piffaretti"
     GIT_COMMITTER_EMAIL: "gpiffaretti@gmail.com"